### ISSUE TITLE
master branch checkout이후  java problem

### ISSUE THREAD

**Issue by wkimdev** [basquiat78/upbit-api-with-telegram#1]
#### 현상 
master brach checkout, 최신 branch인 websocket-api-v0.1 두개다 checkout 을 받았는데 아래 java 에러가 나네요~!

## (1) log cannot be resolved
- @Slf4j 이 붙은 곳에서 전부 에러가 나는걸 보니 제가 뭔가 설정을 추가하지 못해서 생긴 것 같기도 한데.. 더 찾아보겠습니다 ㅜ 

## (2) The constructor Candle  .... is undefined
- `The constructor Candle(String, String, String, Double, Double, Double, Double, long, Double, Double) is undefined`
- 발생 위치 : Days.java, Minutes.java.. 

## (3) The method builder() is undefined for the type QuotationQuery
- 발생 위치 :  CandlesService, TradesService.. 

## (4) The method getQuery() is undefined for the type RequestQuery
- 발생 위치 : GenerateService.java
  
기타 등등..  

- project git clone받구, maven update,,, project clean.., junit 4,  추가 하라고 해서 추가했습니다.

**Comment by basquiat78** [comment]
지금 내용은 딱 롬복설정 문제인데...

**Comment by wkimdev** [comment]
아 넵 확인했었는데 이슈 클로즈 시키는걸 깜박했습니다 감사합니다~!
